language: node_js
node_js:
  - 10

branches:
  only:
    - master
    - dev

sudo: false

install:
  - npm install riot@4.0.0-alpha.8 && npm i

cache:
  directories:
    - node_modules

notifications:
    email: false